<#
    Concurrency, and the difference between "nothing crashed" and "the answer is right".

    Three defects, all found by driving real processes rather than by reading:

      - a domain controller whose network performance counters are broken was sampled as a MEASURED
        zero packets/sec and reported green, "the server has enough resources";
      - a wait documented as bounded was bounded per job inside a sequential loop, so N wedged
        servers cost N budgets;
      - each individual file write was serialised, but the report SET was not, so two overlapping
        runs left an HTML from one scan beside a JSON and a remediation script from another.

    The third is the one worth stating plainly: the HTML tells the operator to execute
    Fix-MdiReadiness-<domain>.ps1 as Domain Admin against production domain controllers. Handing them
    one generated by a different scan is not an untidy output directory.
#>

$ErrorActionPreference = 'Stop'
$here = $PSScriptRoot
$target = Join-Path $here 'Test-MdiReadiness.ps1'
if (-not (Test-Path $target)) { $target = Join-Path (Split-Path $here -Parent) 'Test-MdiReadiness.ps1' }
if (-not (Test-Path $target)) { throw "Test-MdiReadiness.ps1 not found from $here" }
$text = Get-Content -LiteralPath $target -Raw

$body = $text -replace '(?m)^\s*#Requires.*$', '' -replace '(?m)^\s*\[CmdletBinding\(.*$', ''
$idx = $body.IndexOf('#region Main'); if ($idx -gt 0) { $body = $body.Substring(0, $idx) }
Invoke-Expression $body
function Write-mdiVerbose { param($Message) }
function Write-mdiWarning { param($Message) }

$script:pass = 0; $script:fail = 0
function Assert-That($name, $condition, $extra = '') {
    if ($condition) { $script:pass++; Write-Host "  PASS  $name" -ForegroundColor DarkGray }
    else { $script:fail++; Write-Host "  FAIL  $name $extra" -ForegroundColor Red }
}

Write-Host 'A counter that returned nothing is not a counter that returned zero' -ForegroundColor Cyan
# The sampler ran "$total += [double] $adapter.PacketsPersec". [double] of a missing value is 0 -
# not an error, not a null, a clean zero - so a server with broken perf counters produced a MEASURED
# zero. Every downstream guard tests "$null -ne $_.PacketsPerSec", which can never be false once the
# sum has been taken, so the report said "enough resources at 0 busy packets/sec" in green about a
# production domain controller nobody had measured.
$sampler = [scriptblock]::Create($script:mdiTrafficSampleScript)
function Invoke-Sampler($adapterRows) {
    $script:fakeAdapters = $adapterRows
    function global:Get-WmiObject {
        param($ComputerName, $Namespace, $Class, $Property, $Filter, $Query, $ErrorAction)
        if ($Class -like '*NetworkInterface*') { return $script:fakeAdapters }
        $null
    }
    try { & $sampler 'dc1' 1 1 'Win32_PerfFormattedData_Tcpip_NetworkInterface' 'cpu' 'mem' 'isatap|Loopback' }
    finally { Remove-Item Function:\global:Get-WmiObject -ErrorAction SilentlyContinue }
}

$broken = Invoke-Sampler @([PSCustomObject]@{ Name = 'Ethernet'; PacketsPersec = $null })
Assert-That 'an adapter with no counter value yields NO sample' ($null -eq $broken) `
    "(got $(if ($null -ne $broken) { $broken[0].PacketsPerSec } else { 'null' }))"

$emptyText = Invoke-Sampler @([PSCustomObject]@{ Name = 'Ethernet'; PacketsPersec = '' })
Assert-That 'an empty counter string yields no sample either' ($null -eq $emptyText)

# The false-red guard. A genuinely idle domain controller really does report 0, and that IS a
# measurement - it must survive, or the fix trades one wrong answer for another.
$idle = Invoke-Sampler @([PSCustomObject]@{ Name = 'Ethernet'; PacketsPersec = 0 })
Assert-That 'a genuinely idle adapter still produces a measured zero' (
    $null -ne $idle -and @($idle)[0].PacketsPerSec -eq 0) "(got '$(@($idle)[0].PacketsPerSec)')"

$busy = Invoke-Sampler @([PSCustomObject]@{ Name = 'Ethernet'; PacketsPersec = 4200 })
Assert-That 'a busy adapter is measured normally' ($null -ne $busy -and @($busy)[0].PacketsPerSec -eq 4200)

# One readable adapter beside one broken one is still a measurement, of the readable one.
$mixed = Invoke-Sampler @(
    [PSCustomObject]@{ Name = 'Ethernet'; PacketsPersec = 1000 }
    [PSCustomObject]@{ Name = 'Ethernet 2'; PacketsPersec = $null })
Assert-That 'a readable adapter beside a broken one still measures' (
    $null -ne $mixed -and @($mixed)[0].PacketsPerSec -eq 1000) "(got '$(@($mixed)[0].PacketsPerSec)')"

# And the verdict that reads the sample must say NOT MEASURED rather than sufficient.
$verdict = Get-mdiCapacityPlanning -ComputerName 'dc1' -TrafficSample $null 3>$null
Assert-That 'no sample renders as not-measured, not as sufficient capacity' (
    [string] $verdict.isCapacityOk -eq 'N/A') "(got '$($verdict.isCapacityOk)')"
Assert-That '  and it never claims "enough resources"' ([string] $verdict.details.Detail -notmatch 'enough resources')

Write-Host 'A bounded wait is bounded for the PHASE, not once per server' -ForegroundColor Cyan
# The jobs run concurrently in a runspace pool, so waiting for them one at a time and charging each
# the full budget is an accounting error: three wedged domain controllers took 3 x 121s.
Assert-That 'the wait deadline is shared across the pending jobs' ($text -match '\$totalWaitMs')
# Shape-independent: what matters is that the remaining budget is TOTAL MINUS ELAPSED, not which
# clamp is wrapped around it. This assertion used to pin the exact literal
# "[int] [Math]::Max(0, $totalWaitMs" and broke when that expression gained an Int32 ceiling - a
# change that strengthened the behaviour rather than weakening it. Per this project's rule that a
# test breaking on a behaviour-preserving refactor is the wrong test, it now checks the relationship
# instead of the spelling. The clamp's actual BEHAVIOUR - no overflow, no server silently nulled,
# a spent budget still flooring at zero - is covered behaviourally by
# CapacityWaveBudgetDoesNotOverflow.Tests.ps1.
Assert-That '  and each wait asks only for the REMAINING budget' (
    $text -match '(?s)\$remainingMs\s*=.{0,200}?\$totalWaitMs\s*-\s*\$waitTimer\.Elapsed\.TotalMilliseconds')
Assert-That '  measured on a monotonic stopwatch, not the wall clock' (
    $text -match '\$waitTimer\s*=\s*\[System\.Diagnostics\.Stopwatch\]::StartNew\(\)')
# It must still scale with WAVES, or a forest larger than the pool throttle would abandon jobs that
# had not been given a chance to start.
Assert-That '  and the budget scales with pool waves, not with a flat deadline' ($text -match '\$waveCount')

# The arithmetic itself, exercised rather than asserted about.
function Get-Budget($jobCount, $throttle, $durationSeconds) {
    $perJob = ([Math]::Max(1, $durationSeconds) * 1000) + 120000
    $waves = [Math]::Max(1, [Math]::Ceiling($jobCount / [double] [Math]::Max(1, $throttle)))
    [double] $perJob * $waves
}
Assert-That 'three concurrent jobs share one budget' ((Get-Budget 3 3 1) -eq (Get-Budget 1 1 1))
Assert-That '  fifty jobs through a pool of fifty also share one' ((Get-Budget 50 50 1) -eq (Get-Budget 1 1 1))
Assert-That '  but a hundred jobs through a pool of fifty get two' ((Get-Budget 100 50 1) -eq (2 * (Get-Budget 1 1 1)))
Assert-That '  and a throttle of zero does not divide by zero' ((Get-Budget 10 0 1) -gt 0)

Write-Host 'The report SET is written under one lock' -ForegroundColor Cyan
# Each individual write was already serialised and retried. The set was not, so the last writer of
# each of the three artefacts could be a different run - and they cross-reference each other.
Assert-That 'a mutex covers the whole artefact-writing phase' ($text -match 'MdiReadinessReportSet_')
Assert-That '  it is released in a finally' ($text -match 'ReleaseMutex')
# An abandoned mutex means the previous holder died. WaitOne THROWS in that case but the lock IS
# taken, so treating the throw as failure would leave the run holding a mutex it never releases.
Assert-That '  an abandoned mutex counts as acquired' ($text -match 'AbandonedMutexException')
# Failure to take the lock must not end the run - a report is still better than no report.
Assert-That '  and failing to acquire it warns rather than aborts' (
    $text -match 'may come from different scans')

# Presence is not enough: a lock taken AFTER the writes, or released BEFORE them, protects nothing.
# The ORDER is the whole point, so it is asserted directly. (Mutation testing caught this: renaming
# the mutex left every presence assertion green because the fallback name still matched.)
$posAcquire = $text.IndexOf('$reportSetHeld = $reportSetMutex.WaitOne(')
$posRemediation = $text.IndexOf('$remediation = New-mdiRemediationScript')
$posHtml = $text.IndexOf('$htmlReportFile = Set-MdiReadinessReport')
$posRelease = $text.IndexOf('$reportSetMutex.ReleaseMutex()')
Assert-That '  the lock is taken before the remediation script is written' (
    $posAcquire -gt 0 -and $posRemediation -gt $posAcquire) "(acquire=$posAcquire remediation=$posRemediation)"
Assert-That '  the HTML is written while it is still held' (
    $posHtml -gt $posRemediation) "(html=$posHtml)"
Assert-That '  and it is released only after the HTML' (
    $posRelease -gt $posHtml) "(release=$posRelease)"

# All three artefacts must sit inside ONE try whose finally does the release, or an exception midway
# leaves the mutex held for the lifetime of the process and every later run blocks on it.
$guardedRegion = if ($posAcquire -gt 0 -and $posRelease -gt $posAcquire) {
    $text.Substring($posAcquire, $posRelease - $posAcquire)
} else { '' }
Assert-That '  all three writes sit inside the guarded region' (
    $guardedRegion -match 'New-mdiRemediationScript' -and $guardedRegion -match 'Set-MdiReadinessReport')
Assert-That '  and the release is reached through a finally' ($guardedRegion -match '\}\s*finally\s*\{')

# The mutex really does exclude a second holder. Proven with a real second process, because a
# same-process WaitOne on a mutex the thread already owns succeeds by re-entrancy and would prove
# nothing at all.
$mutexName = 'MdiReadinessReportSet_TEST_{0}' -f ([guid]::NewGuid().ToString('N'))
$held = New-Object System.Threading.Mutex($false, $mutexName)
$acquiredHere = $held.WaitOne(0)
Assert-That 'the lock is acquired by the first holder' $acquiredHere
$probe = @"
`$m = New-Object System.Threading.Mutex(`$false, '$mutexName')
try { if (`$m.WaitOne(0)) { 'ACQUIRED' } else { 'BLOCKED' } } catch [System.Threading.AbandonedMutexException] { 'ACQUIRED' }
"@
$probeFile = Join-Path $env:TEMP ('mdi-mutex-{0}.ps1' -f ([guid]::NewGuid().ToString('N')))
[IO.File]::WriteAllText($probeFile, $probe)
$prevEap = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
$second = (& "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -File $probeFile 2>&1 | Out-String).Trim()
$ErrorActionPreference = $prevEap
Assert-That '  a SECOND PROCESS is blocked while it is held' ($second -match 'BLOCKED') "(second process said '$second')"
[void] $held.ReleaseMutex()
$third = (& "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -ExecutionPolicy Bypass -File $probeFile 2>&1 | Out-String).Trim()
Assert-That '  and acquires it once released' ($third -match 'ACQUIRED') "(said '$third')"
$held.Dispose()
Remove-Item $probeFile -Force -ErrorAction SilentlyContinue

# Two different domains, or two different output paths, must never wait on each other.
$keyA = ('C:\reports|contoso.com').ToLowerInvariant()
$keyB = ('C:\reports|fabrikam.com').ToLowerInvariant()
$keyC = ('D:\other|contoso.com').ToLowerInvariant()
function Get-Hash($k) {
    [System.BitConverter]::ToString([System.Security.Cryptography.SHA256]::Create().ComputeHash(
            [System.Text.Encoding]::UTF8.GetBytes($k))).Replace('-', '').Substring(0, 32)
}
Assert-That 'two domains get different locks' ((Get-Hash $keyA) -ne (Get-Hash $keyB))
Assert-That 'two output paths get different locks' ((Get-Hash $keyA) -ne (Get-Hash $keyC))
Assert-That 'the same scan gets the same lock whatever the casing' ((Get-Hash $keyA) -eq (Get-Hash ('C:\REPORTS|CONTOSO.COM').ToLowerInvariant()))

Write-Host "================ $script:pass passed / $script:fail failed ================"
if ($script:fail -gt 0) { exit 1 }
